### PR TITLE
QA env Images update script

### PR DESCRIPTION
**Pull request by slemrmartin**
This will update existing image streams in topological-inventory-qa env from quay (based on the `qa` tag)

### CODE REVIEW

**Comment by slemrmartin** [comment]
@lindgrenj6 there aren't new images like google or scheduler. how to update them?

**Comment by syncrou** [comment]
@slemrmartin is the plan with this to add the update script to guides so we have it available to all of us? Just making sure I understand this PR.

**Comment by slemrmartin** [comment]
@syncrou yes, for everyone with permissions. 
I want to collect all scripts related to us from other repos to have everything in a single (this one) repo

**Comment by lindgrenj6** [comment]
@slemrmartin the stable tag probably hasn't been created since there isn't a stable branch for them yet, probably need to push a branch for each of those then run the builds manually.

**Comment by slemrmartin** [comment]
@syncrou can you merge it?

**Review by syncrou — APPROVED** [review]
Nice to have this here!  LGTM 👍

**Pull request merged**
