### PR TITLE
Add script to run topological-host-inventory-sync

### PR DESCRIPTION
**Pull request by lpichler**
@miq-bot assign @slemrmartin 

we need to put config.sh but it is in `.gitignore`

```
# Topological Host Inventory Service
export TOPOLOGICAL_HOST_INVENTORY_SYNC_DIR="$root_dir/topological_inventory-host_inventory_sync"
export HOST_INVENTORY_API="localhost"
export PATH_PREFIX="api"
export APP_NAME="topological-inventory"
```

### CODE REVIEW

**Comment by slemrmartin** [comment]
@lpichler `config.sh` is in gitignore and has to include `config.default.sh`, which doesn't contain any secrets. 
Maybe you have previous version of this config structure without default config. 
[see default_config](https://github.com/ManageIQ/topological_inventory-guides/blob/master/scripts/config.default.sh).

**Review by slemrmartin — CHANGES_REQUESTED** [review]
please add `$TOPOLOGICAL_HOST_INVENTORY_SYNC_DIR` to default config
and don't define PATH_PREFIX and APP_NAME as global variables, because they are shared across services. Instead define them in script directly, like https://github.com/ManageIQ/topological_inventory-guides/blob/master/scripts/services/topological-api.sh

**Comment by lpichler** [comment]
Per discussion with @slemrmartin this will be most likely finished by @pkomanek.

**Comment by slemrmartin** [comment]
closing, topo is gone

**Pull request closed without merging**
